### PR TITLE
Update OpenTelemetry SDK to 1.12.0

### PR DESCRIPTION
**Pull request by RangelReale**

### CODE REVIEW

**Review by pichlermarc — APPROVED** [review]
This looks great, thank you for your contribution!
Just one small suggestion to get the lint step to pass :slightly_smiling_face:

**Review by dyladan — APPROVED** [review]
Thanks for updating the readme. LGTM. I approved the test run so after that finishes we should be good to go here.

**Review by pirgeo — APPROVED** [review]

**Comment by arminru** [comment]
@RangelReale
Your changes are included in our https://github.com/dynatrace-oss/opentelemetry-metric-python/releases/tag/v0.3.0 which you can find on https://pypi.org/project/opentelemetry-exporter-dynatrace-metrics/0.3.0/.
Thank you!

**Comment by RangelReale** [comment]
> @RangelReale Your changes are included in our https://github.com/dynatrace-oss/opentelemetry-metric-python/releases/tag/v0.3.0 which you can find on https://pypi.org/project/opentelemetry-exporter-dynatrace-metrics/0.3.0/. Thank you!

Will update my dependencies, thanks!

**Pull request merged**
